//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public string Name { get; set; }
        public string Password { get; set; }
        public string Color { get; set; }
        public string Data { get; set; }
        public int ChildID { get; set; }
    }
}
