//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LearnHebrewDbContext : DbContext
    {
        public LearnHebrewDbContext()
            : base("name=LearnHebrewDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adult> Adults { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<ChildToAdult> ChildToAdults { get; set; }
        public virtual DbSet<ChildToGame> ChildToGames { get; set; }
        public virtual DbSet<ChildToUnseen> ChildToUnseens { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Unseen> Unseens { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<ChildProgress> ChildProgresses { get; set; }
    }
}
